---
# defaults for manageiq-apb

playbook_debug: no
application_init_delay: "{{ lookup('env','APPLICATION_INIT_DELAY') | default('60', true) }}"
database_region: "{{ lookup('env','DATABASE_REGION') | default('1', true) }}"
database_service_name: "{{ lookup('env','DATABASE_SERVICE_NAME') | default('manageiq-postgresql', true) }}"
memcached_max_connections: "{{ lookup('env','MEMCACHED_MAX_CONNECTIONS') | default('1024', true) }}"
memcached_max_memory: "{{ lookup('env','MEMCACHED_MAX_MEMORY') | default('64', true) }}"
memcached_slab_page_size: "{{ lookup('env','MEMCACHED_SLAB_PAGE_SIZE') | default('1M', true) }}"
memcached_service_name: "{{ lookup('env','MEMCACHED_SERVICE_NAME') | default('manageiq-memcached', true) }}"
manageiq_memcached_port: "tcp://{{ lookup('env','MEMCACHED_SERVICE_NAME') | default('manageiq-memcached', true) }}:11211"
manageiq_memcached_port_11211_tcp: "tcp://{{ lookup('env','MEMCACHED_SERVICE_NAME') | default('manageiq-memcached', true) }}:11211"
manageiq_memcached_port_11211_tcp_addr: "{{ lookup('env','MEMCACHED_SERVICE_NAME') | default('manageiq-memcached', true) }}"
manageiq_memcached_service_host: "{{ lookup('env','MIQ_MEMCACHED_SERVICE_HOST') | default('manageiq-memcached', true) }}"
manageiq_postgresql_port: "tcp://{{ lookup('env','MIQ_POSTGRESQL_SERVICE_HOST') | default('manageiq-postgresql', true) }}:5432"
manageiq_postgresql_port_5432_tcp: "tcp://{{ lookup('env','MIQ_POSTGRESQL_SERVICE_HOST') | default('manageiq-postgresql', true) }}:5432"
manageiq_postgresql_5432_tcp_addr: "{{ lookup('env','MIQ_POSTGRESQL_SERVICE_HOST') | default('manageiq-postgresql', true) }}"
manageiq_postgresql_service_host: "{{ lookup('env','MIQ_POSTGRESQL_SERVICE_HOST') | default('manageiq-postgresql', true) }}"
namespace: "{{ lookup('env','NAMESPACE') | default('manageiq-apb', true) }}"
openshift_target: "{{ lookup('env','OPENSHIFT_TARGET') }}"
openshift_user: "{{ lookup('env','OPENSHIFT_USER') }}"
openshift_pass: "{{ lookup('env','OPENSHIFT_PASS') }}"
postgresql_database: "{{ lookup('env','POSTGRESQL_DATABASE') | default('vmdb_production', true) }}"
postgresql_password: "{{ lookup('env','POSTGRESQL_PASSWORD') | default('admin', true) }}"
postgresql_user: "{{ lookup('env','POSTGRESQL_USER') | default('admin', true) }}"
