---
- name: set volume claim state to {{ state }}
  k8s_v1_persistent_volume_claim:
    name: "{{ service_name }}"
    namespace: "{{ namespace }}"
    labels:
      app: rhscl-mysql-apb
      service: "{{ service_name }}"
    state: present
    access_modes:
      - ReadWriteOnce
    resources_requests:
      storage: "{{ volume_size }}"
    state: "{{ state }}"

- name: set MySQL deployment using persistent storage to {{ state }}
  openshift_v1_deployment_config:
    name: "{{ service_name }}"
    namespace: "{{ namespace }}"
    labels:
      app: rhscl-mysql-apb
      service: "{{ service_name }}"
    replicas: 1
    selector:
      app: rhscl-mysql-apb
      service: "{{ service_name }}"
    spec_template_metadata_labels:
      app: rhscl-mysql-apb
      service: "{{ service_name }}"
    containers:
    - name: mysql
      image: "{{ image }}"
      env:
      - name: MYSQL_USER
        value: "{{ mysql_user }}"
      - name: MYSQL_PASSWORD
        value: "{{ mysql_password }}"
      - name: MYSQL_DATABASE
        value: "{{ mysql_database }}"
      ports:
      - name: mysql
        protocol: TCP
        container_port: 3306
      liveness_probe:
        timeout_seconds: 1
        inital_delay_seconds: 30
        tcp_socket:
          port: 3306
      readiness_probe:
        timeout_seconds: 1
        initial_delay_seconds: 5
        _exec:
          command:
          - "/bin/sh"
          - "-i"
          - "-c"
          - "MYSQL_PWD=\"$MYSQL_PASSWORD\" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE -e 'SELECT 1'"
      volume_mounts:
      - mount_path: /var/lib/mysql/data
        name: mysql-data
    volumes:
    - name: mysql-data
      persistent_volume_claim:
        claim_name: "{{ service_name }}"
    triggers:
    - type: ConfigChange
    state: "{{ state }}"
    # TODO: use ImageChange trigger / Image Streams?
